# Generated by Django 6.0.3 on 2026-03-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('legal_domain', models.CharField(blank=True, choices=[('criminal', 'Criminal Law'), ('civil', 'Civil Law'), ('labour', 'Labour Law'), ('family', 'Family Law'), ('consumer', 'Consumer Law'), ('cyber', 'Cyber Law')], max_length=50, null=True)),
                ('sections_cited', models.JSONField(blank=True, null=True)),
                ('escalated_to_lawyer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
